# Generated by Django 5.0.6 on 2024-06-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='ano_fabricacion',
            field=models.PositiveIntegerField(),
        ),
    ]
